# Generated by Django 5.1 on 2024-10-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promo', models.CharField(max_length=250, verbose_name='Nombre Promo')),
                ('valor_promo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Promo')),
                ('cant_bidones', models.IntegerField(verbose_name='Cantidad Bidones')),
                ('alta_promo', models.DateField(auto_now_add=True, verbose_name='Fecha Alta Promo')),
                ('vencimiento_promo', models.DateField(verbose_name='Fecha Fin Promo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Promo')),
                ('nota', models.TextField(verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['id'],
            },
        ),
    ]
