# Generated by Django 5.1 on 2024-10-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['-id'], 'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterField(
            model_name='promo',
            name='cant_bidones',
            field=models.PositiveIntegerField(verbose_name='Cantidad Bidones'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota'),
        ),
    ]
