# Generated by Django 5.1 on 2024-08-31 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promo', models.CharField(max_length=250, verbose_name='Nombre Promo')),
                ('valor_promo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Promo')),
                ('cant_bidones', models.IntegerField(verbose_name='Cantidad Bidones')),
                ('alta_promo', models.DateField(auto_now_add=True, verbose_name='Fecha Alta Promo')),
                ('vencimiento_promo', models.DateField(verbose_name='Fecha Fin Promo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Promo')),
                ('nota', models.TextField(verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_cobro', models.DateField(verbose_name='Fecha de Cobro')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('tipo_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.promo', verbose_name='Tipo de Promoción')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromoPorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_promo', models.DateField(verbose_name='Inicio de Promo')),
                ('fin_promo', models.DateField(verbose_name='Fin de Promo')),
                ('bidones_disponibles', models.IntegerField(verbose_name='Bidones Disponibles')),
                ('codigo_dispenser', models.CharField(max_length=20, verbose_name='Código Dispenser')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente', verbose_name='Cliente')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.promo', verbose_name='Promoción')),
            ],
            options={
                'verbose_name': 'Promoción por Cliente',
                'verbose_name_plural': 'Promociones por Cliente',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/registro_pagos/clientes', verbose_name='Comprobante')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pago',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(auto_now_add=True, verbose_name='Fecha de Visita')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['fecha_visita'],
            },
        ),
    ]
