# Generated by Django 5.1 on 2024-09-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoporcliente',
            name='bidones_acumulados',
            field=models.IntegerField(default=0, verbose_name='Bidones Acumulados'),
        ),
        migrations.AddField(
            model_name='promoporcliente',
            name='entrega_bidones',
            field=models.IntegerField(default=0, verbose_name='Entrega de Bidones'),
        ),
        migrations.AddField(
            model_name='promoporcliente',
            name='retorno_bidones',
            field=models.IntegerField(default=0, verbose_name='Retorno de Bidones'),
        ),
    ]
