# Generated by Django 5.1 on 2024-09-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_promoporcliente_inicio_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoporcliente',
            name='inicio_promo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inicio de Promo'),
        ),
    ]
