# Generated by Django 5.1 on 2024-09-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_promoporcliente_inicio_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_promo',
        ),
        migrations.AlterField(
            model_name='promoporcliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='cliente.cliente', verbose_name='Cliente'),
        ),
    ]
