# Generated by Django 5.1 on 2024-09-17 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_remove_cliente_tipo_promo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=250, verbose_name='Nombre Producto')),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('alta_producto', models.DateField(auto_now_add=True, verbose_name='Fecha Alta Producto')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Proveedor')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('imagen_url', models.FileField(blank=True, null=True, upload_to='productos/img', verbose_name='Imagen URL')),
                ('descripcion_producto', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Venta')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Venta Producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('descuento', models.PositiveIntegerField(default=0, verbose_name='Descuento')),
                ('precio_unidad_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Venta')),
                ('precio_total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total Venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
                'unique_together': {('venta', 'producto')},
            },
        ),
        migrations.DeleteModel(
            name='RegistroPago',
        ),
    ]
