# Generated by Django 5.1 on 2024-09-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_producto_venta_ventaproducto_delete_registropago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventaproducto',
            options={'ordering': ['id'], 'verbose_name': 'Venta por Producto', 'verbose_name_plural': 'Ventas por Producto'},
        ),
    ]
