# Generated by Django 4.2.2 on 2024-10-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_producto_imagen_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventaproducto',
            options={'ordering': ['-id'], 'verbose_name': 'Venta por Producto', 'verbose_name_plural': 'Ventas por Producto'},
        ),
        migrations.AddField(
            model_name='venta',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Venta'),
        ),
    ]
