# Generated by Django 5.1 on 2024-10-07 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.promo', verbose_name='Promocion Asociada'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.venta', verbose_name='Venta Asociada'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente', verbose_name='Cliente Asociada'),
        ),
    ]
