# Generated by Django 5.1 on 2024-10-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_pagos_promo_pagos_venta_alter_pagos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.producto', verbose_name='Producto Asociada'),
        ),
    ]
