# Generated by Django 5.1 on 2024-10-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_pagos_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='producto',
        ),
    ]
