# Generated by Django 5.1 on 2024-10-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_remove_pagos_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoporcliente',
            name='fecha_pago_promo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Promo'),
        ),
    ]
