# Generated by Django 5.1 on 2024-10-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_promoporcliente_fecha_pago_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_visita'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_cobro',
        ),
    ]
