# Generated by Django 5.1 on 2024-10-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_alter_visita_options_remove_cliente_fecha_cobro'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproducto',
            name='producto',
        ),
        migrations.AlterField(
            model_name='promoporcliente',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promociones.promo', verbose_name='Promoción'),
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='venta',
        ),
        migrations.AlterUniqueTogether(
            name='ventaproducto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='visita',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='VentaProducto',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
