# Generated by Django 5.1 on 2024-10-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0016_remove_ventaproducto_producto_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Venta')),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Venta')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Venta Producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('descuento', models.PositiveIntegerField(default=0, verbose_name='Descuento')),
                ('precio_unidad_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Venta')),
                ('precio_total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total Venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Venta por Producto',
                'verbose_name_plural': 'Ventas por Producto',
                'ordering': ['-id'],
                'unique_together': {('venta', 'producto')},
            },
        ),
    ]
